
my:
  greeting: Hello World from config server
  list:
    values: one,two,three,four

db:
  connection: connection-string-here-from-config-server
  host: 128.0.0.1
  port: 3600

management.endpoints.web.exposure.include: "*"
